package main

import (
    "fmt"
	"log" // Source: https://pkg.go.dev/log
    "example.com/greetings"
)

func main() {
	// Set properties of the log package.
	log.SetPrefix("greetings: ") // Sets the prefix that will be added to each log message generated by the log package. "greetings: error message"
	log.SetFlags(2) // The flags determine what additional information will be shown in the message. 2 should mean Ldate and Ltime. https://pkg.go.dev/log#Ldate

	// Request a greeting message.
	

    // Get a greeting message and print it.
    message := greetings.Hello("Gladys")
    fmt.Println(message)
}