package main

import (
    "fmt"
	"log" // Source: https://pkg.go.dev/log
    "example.com/greetings"
)

func main() {
	// Set properties of the log package.
	log.SetPrefix("greetings: ") // Sets the prefix that will be added to each log message generated by the log package. "greetings: error message"
	log.SetFlags(2) // The flags determine what additional information will be shown in the message. 2 should mean Ldate and Ltime. https://pkg.go.dev/log#Ldate

	// Request a greeting message.
	// Function call.
	message, err := greetings.Hello("Justin")
	// Calling the Hello function from the greetings package.
	// ("") (Empty string) Is getting passed to the Hello function.
	// The Hello function will return its message and error depending on what is passed here.
	// The return value goes into message and err.
	// message and err are declared.

	if err != nil {
		log.Fatal(err)
	}
	// if err is not null.
	// Function call on log.Fatal passing err.
	// Prints string err to the console. 
	// Exits.

    // If no errors, prints the returned message.
    fmt.Println(message)
}

// Output
// Error
	// greetings: 16:33:18 empty name
	// exit status 1